apiVersion: v1
data:
  default.conf: "server {\n  listen 80;\n  server_name _;\n  \n  location / {\n  \
    \  root /usr/share/nginx/html;\n    index index.html;\n  }\n  \n  location /api\
    \ {\n    proxy_pass http://backend-api:8080;\n  }\n}\n"
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: my-app
